# fly.toml app configuration file generated for nano-clean-api on 2026-05-05T12:42:44-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nano-clean-api'
primary_region = 'dfw'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
